[db]
host="127.0.0.1"
port=3306
user="root"
password="123456"
database="test"
charset="utf8mb4"

[cfg]
outDir="./model"
tableNames=["user"]
packageName="model"
needTag=["gorm", "json"]
upperFirstLetter=false
humpNaming=false
importOtherType="./fieldOtherType.json"
