[db]
host="127.0.0.1"
port=55000
user="root"
password="123456"
database="miajiodb"
charset="utf8mb4"

[cfg]
outDir="./model"
tableNames=["user"]
packageName="model"
needTag=["gorm", "json"]
upperFirstLetter=false
humpNaming=false
importOtherType="./fieldOtherType.json"
webServer=false

# [application]
# port=8080
# useHttps=false
# pemFile=""
# keyFile=""